# This is a basic workflow to help you get started with Actions

name: run_changes

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:      

env:
    LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LB_PROKEY }}
    LIQUIBASE_COMMAND_URL: ${{ secrets.LB_URL }}
    LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LB_USER }}
    LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LB_PASSWORD }}
    LIQUIBASE_DRIVER: ${{ secrets.LB_DRIVER }}
    
#     LIQUIBASE_COMMAND_CHANGELOG_FILE: ${{ secrets.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
    
jobs:

  Build_Job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        curl -L https://github.com/liquibase/liquibase-snowflake/releases/download/liquibase-snowflake-4.8.0/liquibase-snowflake-4.8.0.jar --output liquibase-snowflake-4.8.0.jar
        curl -L https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.13.9/snowflake-jdbc-3.13.9.jar --output snowflake-jdbc-3.13.9.jar
    
    - name: Running Quality Checks
      uses: docker://liquibase/liquibase:4.8.0
      with:
        args: --changeLogFile=Changelogs/snowflake1.xml checks run
      
    - name: Running update
      uses: docker://liquibase/liquibase:4.8.0
      with:
        args: --changeLogFile=Changelogs/snowflake1.xml --classpath=snowflake-jdbc-3.13.9.jar:liquibase-snowflake-4.8.0.jar checks run
